config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}
  resources :bleets

  root "bleets#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bleet.rb
class Bleet < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

       has_many :bleets  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bleets_controller.rb
class BleetsController < ApplicationController
  before_action :set_bleet, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /bleets or /bleets.json
  def index
    @bleets = Bleet.all.order("created_at DESC")
    @bleet = Bleet.new
  end

  # GET /bleets/1 or /bleets/1.json
  def show
  end

  # GET /bleets/new
  def new
    @bleet = current_user.bleets.build
  end

  # GET /bleets/1/edit
  def edit
  end

  # POST /bleets or /bleets.json
  def create
    @bleet = current_user.bleets.build(bleet_params)

    respond_to do |format|
      if @bleet.save
        format.html { redirect_to root_path, notice: "Bleet was successfully created." }
        format.json { render :show, status: :created, location: @bleet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bleet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bleets/1 or /bleets/1.json
  def update
    respond_to do |format|
      if @bleet.update(bleet_params)
        format.html { redirect_to @bleet, notice: "Bleet was successfully updated." }
        format.json { render :show, status: :ok, location: @bleet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bleet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bleets/1 or /bleets/1.json
  def destroy
    @bleet.destroy
    respond_to do |format|
      format.html { redirect_to bleets_url, notice: "Bleet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bleet
      @bleet = Bleet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bleet_params
      params.require(:bleet).permit(:bleet)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
private

def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
    
end

def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
    
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bleets_helper.rb
module BleetsHelper
end

app/views/bleets/_feed.html.erb
<div class="column is-half">
    <% if user_signed_in? %>
    <article class="media box">
        <figure class="media-left ">
            <p class= "image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt:current_user.name) %>
            </p>
        </figure>
        <div class="media-content">
          <%= render 'bleets/form' %>
        </div>
    </article>
    <% end %>

<% @bleets.each do |bleet| %>
   <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is-64x64">
            <%= gravatar_image_tag(bleet.user.email, size: 64, alt:bleet.user.name) %>
        </figure>
      </div> 
      <div class="media-content">
        <div class="content">
            <strong><%= bleet.user.name %></strong><br/>
            <small>@<%= bleet.user.username %></small><br/>
            <p><%= bleet.bleet %></p>
        </div>
        <% if user_signed_in? %>
        <nav class="level">
           <div class="level-left is-mobile">
                <%= link_to bleet, class: "level-item" do %>
                    <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>    
                <% end %>
                <%= link_to edit_bleet_path(bleet), class: "level-item" do %>
                    <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to bleet, method: :delete, data: {confirm: "Are you sure you want to delete this bleet?"
                } do %>
                    <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i></span>
                <% end %>
           </div> 
        </nav>
        <% end %>
      </div>
    </article>
   </div>
<% end %>
</div>
            
    

app/views/bleets/_form.html.erb
<%= simple_form_for(@bleet) do |f| %>
  <%= f.error_notification %>
  <div class="control">
    <%= f.input :bleet, label: "Bleet Away", input_html: { class: "textarea"}, wrapper: false, 
    label_html: {class: "label"}, placeholder: "Compose a new bleet", autofocus: true %>
  </div>
  <%= f.button :submit, class: "button is-info"  %>
<% end %>

app/views/bleets/_profile.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Profile</p>
		<div class="panel-block">
			<article class="media">
				<div class="media-left">
					<figure class="image is-64x64">
						<%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
					</figure>
				</div>
				<div class="media-content">
					<div class="content">
						<p>
							<strong><%= current_user.name %></strong><br />
							<small>@<%= current_user.username %></small>
						</p>
					</div>
				</div>
			</article>
		</div>
		<div class="panel-block">
			<div class="level is-mobile">
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Bleets</p>
						<p class="title is-6"><%= current_user.bleets.count %></p>
					</div>
				</div>
				<div class="level-item has-centered-text">
					<div>
						<p class="heading">Following</p>
						<p class="title is-6">123</p>
					</div>
				</div>
					<div class="level-item has-centered-text">
					<div>
						<p class="heading">Followers</p>
						<p class="title is-6">465K</p>
					</div>
				</div>
			</div>
		</div>
	</nav>
</div>

app/views/bleets/_trends.html.erb
<div class="column is-one-quarter">
	<nav class="panel">
		<p class="panel-heading">Trends</p>
		<a class="panel-block">
			Trend 1
		</a>
		<a class="panel-block">
			Trend 2
		</a>
		<a class="panel-block">
			Trend 3
		</a>
		<a class="panel-block">
			Trend 4
		</a>
		<a class="panel-block">
			Trend 5
		</a>
		<a class="panel-block">
			Trend 6
		</a>
	</nav>
</div>

app/views/bleets/_who-to-follow.html.erb
   
<div class="column">
	<nav class="panel">
		<p class="panel-heading">Who to Follow</p>
	
	<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Neha Lalwani</strong>
						<small>@nehal</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Neha Lalwani</strong>
						<small>@nehal</small>
					</p>
				</div>
			</div>
		</article>
	</div>
		<div class="panel-block">
		<article class="media">
			<div class="media-left">
				<figure class="image is-32x32">
					<img src="https://bulma.io/images/placeholders/64x64.png">
				</figure>
			</div>
			<div class="media-content">
				<div class="content">
					<p>
						<strong>Neha Lalwani</strong>
						<small>@nehal</small>
					</p>
				</div>
			</div>
		</article>
	</div>
	</nav>
</div>

app/views/bleets/edit.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Editing Tweeet</h1>
				<%= render 'form', tweeet: @bleet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', bleets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/bleets/index.html.erb
<section class= "section" >
  <div class="container">
    <div class="columns">
    <% if user_signed_in? %>
    <%= render 'profile' %>
    <% else %>
      <%= render 'trends' %>
      <% end %>

      
      <%= render 'feed' %>
      <%= render 'who-to-follow' %>
    </div>
  </div>
</section>

app/views/bleets/new.html.erb
<div class="section">
	<div class="container">
		<div class="columns is-centered">
			<div class="column is-half">
				<h1 class="title">Create a new Bleet</h1>
					<%= render 'form', bleet: @bleet %>
			</div>
		</div>
	</div>
</div>

<nav class="navbar is-fixed-bottom">
	<div class="navbar-menu">
		<div class="navbar-item">
			<div class="field is-grouped">
				<p class="control">
					<%= link_to 'Cancel', bleets_path, class: "button is-dark" %>
				</p>
		</div>
	</div>
</nav>

app/views/bleets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bleet:</strong>
  <%= @bleet.bleet %>
</p>

<%= link_to 'Edit', edit_bleet_path(@bleet) %> |
<%= link_to 'Back', bleets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bleater</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
      <p class="notice"><%= notice %></p>
      </div>
      <% end %>
      <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
      </div>
      <% end %>
      
      <nav class="navbar is-info">
        <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
        <h1 class="title is-5">Bleeter</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExample">
        <span></span>
        <span></span>
        <span></span>
        </div>
       </div>

        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to 'New Bleet', root_path, class: "button is-info is-inverted" %>
              </p>
              <% if user_signed_in? %>
                <p class="control">
                  <%= link_to current_user.name, edit_user_registration_path, class: "button is-info" %>
                </p>
                <p>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "button is-info" %>
                </p>
              <% else %>

              <p class="control">
                <%= link_to 'Sign In', new_user_session_path, class: "button is-info" %>
              </p>

              <p class="control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
              </p> 
              <% end %> 
            
            </div>
          </div>
        </div>
      </nav>


    <%= yield %>
  </body>
</html>